[metadata]
name = aiidalab-feff
version = 0.1.0a1
description = AiiDAlab app for FEFF-based EXAFS and MD-EXAFS calculations
author = J. Kane Shenton

[aiidalab]
title = AiiDAlab FEFF
description = AiiDAlab app for FEFF-based EXAFS and MD-EXAFS calculations
authors = J. Kane Shenton
logo = logo.svg
categories =
    spectroscopy
state = development
